### ISSUE TITLE
Support for rewrite-target annotation

### ISSUE THREAD

**Issue by AndyBarron** [kubernetes/ingress-gce#124] opened 2018-02-04 08:28 UTC
https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md#url-related

This has been a pain point for us deploying microservices on GKE. We need `static-ip-name`, so we can't switch to the Nginx ingress.

**Comment by nicksardo** [comment] 2018-02-07 17:32
Dupe of #109

**Closed by nicksardo** 2018-02-07 17:32 UTC
