### ISSUE TITLE
support for session affinity

### ISSUE THREAD

**Issue by leo-baltus** [kubernetes/ingress-gce#64] opened 2017-10-31 13:43 UTC
The GCE loadbalancer has support for session affinity, either by client-ip or a generated cookie. As far as i know there is no way to specify this in an ingress manifest. 

It would be very useful to have this functionality.

**Comment by nicksardo** [comment] 2017-11-15 19:23
Dupe of #28

**Closed by nicksardo** 2017-11-15 19:23 UTC
