### ISSUE TITLE
How to enable Global Access for HTTP internal load balancer? 

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/ingress-gce#1887] opened 2022-12-19 15:47 UTC
Hi!, I'm trying to use gce controller with following annotations, to enable Global Access on the frontend configuration. 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
```

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce-internal
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
```

from this https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#service_parameters. docs, it does work for L4 LB but it doesn't for L7 internal.

**Comment by spencerhance** [comment] 2023-01-24 00:10
This looks like a dupe of #1883

Unfortunately this is not something we have planned for GKE Ingress.  It will however be implemented by [GKE Gateway](https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api), although I can't provide an exact ETA.

**Comment by mat-613** [comment] 2023-04-06 09:56
+1

**Closed** 2024-02-18 11:58 UTC
Labels: kind/feature, lifecycle/rotten
