### ISSUE TITLE
Custom response headers support?

### ISSUE THREAD

**Issue by aleks-m** [kubernetes/ingress-gce#1106] opened 2020-05-20 10:49 UTC
Hi.

Is there a way to configure custom response headers on path or load balancer level?

Thanks.

**Comment by rramkumar1** [comment] 2020-05-21 13:38
@aleks-m Do you mean headers sent back to the client? Can't you do that in your application?

**Comment by aleks-m** [comment] 2020-05-21 14:02
@rramkumar1 yes.

Well, in theory I can. But in my case I have multiple apps behind one load balancer and it will be pretty hard to modify all of them (especially given the fact what they are written in different programming languages). And such approach will be impossible if I run a third-party app with no source code provided and with no header configuration support.
Would be much better to just set response headers on a load balancer instead of modifying each app source code.

**Comment by rramkumar1** [comment] 2020-05-21 14:54
@mark-church any thoughts? I don't think there is a GCLB feature for this nor can I find a feature request.

**Comment by bowei** [comment] 2020-05-21 15:28
This is not available right now, we'll update when it is possible on the underlying product.

**Comment by lorenzozimolo** [comment] 2020-09-28 06:52
The feature has been released in beta in GCLB 3 days ago.
https://issuetracker.google.com/issues/62051227

**Comment by jeremyd** [comment] 2021-02-10 21:49
I need this feature for HSTS.  Can we unfreeze this?

**Comment by bowei** [comment] 2021-02-10 21:59
I might be not understanding frozen status -- I use it to pin issues so they do not rot

**Comment by jeremyd** [comment] 2021-02-10 22:17
Apologies @bowei I assumed frozen meant something bad.  I see now that it prevents auto-close.  Thanks for clarifying.

**Comment by ivan046** [comment] 2021-05-29 15:05
> 
> 
> This is not available right now, we'll update when it is possible on the underlying product.

Hello @bowei! This is definitely supported by GCE load balancers (https://cloud.google.com/load-balancing/docs/custom-headers#working-with-response). Tested succesfully by manually adding custom responce headers (including CORS like Access-Control-Allow-Origin) to NEGs configured with Ingress BackendConfigs. Please, implement this feature. Response headers (mostly CORS ones) is a core feature that will let many people to get rid of ingress-nginx installed between ingress-gce and k8s services. Thanks!

**Comment by cgotfried** [comment] 2021-06-23 14:45
I made a request for allowing Custom Response Headers from GKE, via a BackendConfig resource. This is essential for enforcing HSTS from a site served by a GKE cluster. The only workaround is to modify the load balaner settings generated by GKE, and that is not a clean approach. Vote for the feature at : https://issuetracker.google.com/issues/191700241

**Comment by aleks-m** [comment] 2021-09-07 11:38
@cgotfried I can't vote on that issue - I got "access denied" then I tried to open that issue tracker URL.

**Comment by nealharris** [comment] 2021-09-14 16:29
same, I'd like to vote for this, but cannot

**Comment by cgotfried** [comment] 2021-09-14 17:05
@aleks-m , @nealharris I don't know why this is happening. The issue is not reachable in the Google issuetracker anymore.
I get Access Denied when i try to go there.
I don't have any way to troubleshoot this.

**Comment by otherguy** [comment] 2021-11-03 10:29
@cgotfried I get the same `Access Denied` error. Could you re-create the issue?

**Comment by albertoal** [comment] 2021-11-18 23:27
Also unable to upvote https://issuetracker.google.com/issues/191700241 - it will be great to have this feature available so we can use HSTS on GKE NEGs

**Comment by dinvlad** [comment] 2022-02-11 22:44
Any updates on this one?

**Comment by m62534** [comment] 2022-03-16 16:37
+1

**Comment by spacejam101** [comment] 2022-06-14 02:42
+1

**Comment by anhnt094** [comment] 2022-07-30 11:08
+1

**Comment by bernardopericacho** [comment] 2022-09-29 03:38
+1

**Comment by ridhoadya** [comment] 2022-10-12 09:08
I found out, there are 3 PR related to this, https://github.com/kubernetes/ingress-gce/pull/1771, https://github.com/kubernetes/ingress-gce/pull/1772, and https://github.com/kubernetes/ingress-gce/pull/1776. But not sure, when it will be release

**Comment by ivan046** [comment] 2022-10-31 16:34
@swetharepakula finally! thanks for the update!

**Comment by red8888** [comment] 2022-12-16 18:47
@swetharepakula any updates? Want to configure this in my manifest instead of having to ask developers to generate custom response headers in code.

**Comment by swetharepakula** [comment] 2022-12-27 19:56
We have released custom response header support. This will be available in new 1.25+ clusters.

**Closed by swetharepakula** 2022-12-27 19:56 UTC
Labels: kind/feature, lifecycle/frozen

**Comment by shield-9** [comment] 2023-01-05 08:19
@swetharepakula Is this feature available for existing GKE 1.25 clusters?
At least, my cluster with v1.25.4-gke.2100 does not have BackendConfig CRD updated.

**Comment by swetharepakula** [comment] 2023-01-26 20:12
@shield-9 , we have started the rollout, but the change has not completely been rolled out to existing clusters. Once rolled out, existing clusters will be upgraded according to maintenance windows with the new version of the ingress controller.

**Comment by gdubicki** [comment] 2023-06-26 15:22
Is it rolled out already? Apart from the docs ☝️ not being updated, there is also no mention of it in the [GKE release notes](https://cloud.google.com/kubernetes-engine/docs/release-notes) and I would expect it to be there.

**Comment by hoexter** [comment] 2023-07-11 07:50
just a bystander, at least in GKE v1.25.10+ it seems to be available, quick and dirty 
```
$ kubectl explain backendconfig --recursive|grep "customResponseHeaders"
    customResponseHeaders	<Object>
```

**Comment by awolfson2** [comment] 2024-08-28 13:01
@swetharepakula - any plans to update the docs on this?
