### ISSUE TITLE
https-only GKE ingress is still showing port 80

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/ingress-gce#290] opened 2018-05-31 18:16 UTC
I have a HTTPS only ingress that shows port 80 in kubectl get (kubectl v1.10.2):

```
# kubectl get ing
NAME       HOSTS     ADDRESS          PORTS     AGE
helloweb   *         35.227.248.205   80, 443   4m
```

I think port 80 actually isn't open:

![image](https://user-images.githubusercontent.com/159209/40799994-f488d8f6-64c3-11e8-9da5-8ff2ee86b31c.png)

describe output:

```
Name:             helloweb
Namespace:        default
Address:          35.227.248.205
Default backend:  helloweb-backend:443 (10.32.4.7:8443)
TLS:
  yourdomain-tls terminates
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     helloweb-backend:443 (10.32.4.7:8443)
Annotations:
  ingress.kubernetes.io/backends:                    {"k8s-be-30921--906590fce6179ef9":"Unknown"}
  ingress.kubernetes.io/https-forwarding-rule:       k8s-fws-default-helloweb--906590fce6179ef9
  ingress.kubernetes.io/https-target-proxy:          k8s-tps-default-helloweb--906590fce6179ef9
  ingress.kubernetes.io/ssl-cert:                    k8s-ssl-09cce9ee44983641-6d1404f893135fac--906590fce6179ef9
  ingress.kubernetes.io/url-map:                     k8s-um-default-helloweb--906590fce6179ef9
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.allow-http":"false"},"labels":{"app":"hello"},"name":"helloweb","namespace":"default"},"spec":{"backend":{"serviceName":"helloweb-backend","servicePort":443},"tls":[{"secretName":"yourdomain-tls"}]}}

  kubernetes.io/ingress.allow-http:  false
Events:
  Type    Reason   Age              From                     Message
  ----    ------   ----             ----                     -------
  Normal  ADD      3m               loadbalancer-controller  default/helloweb
  Normal  CREATE   1m               loadbalancer-controller  ip: 35.227.248.205
  Normal  Service  1m (x3 over 1m)  loadbalancer-controller  default backend set to helloweb-backend:30921
```

My YAML:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  labels:
    app: hello
  annotations:
    kubernetes.io/ingress.allow-http: "false" # disable HTTP
spec:
  tls:
    - secretName: yourdomain-tls
  backend:
    serviceName: helloweb-backend
    servicePort: 443
```

any ideas if this is a kubectl bug?

**Comment by rramkumar1** [comment] 2018-05-31 22:34
@ahmetb Does your service "helloweb-backend" have port 80 as one of the service port's? I'm thinking maybe that kubectl looks at the services your Ingress references and blindly lists all service ports.

**Comment by ahmetb** [comment] 2018-05-31 22:47
It does not mention `80` anywhere. You can view the manifests at https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/hello-app-tls/manifests.

I suspect this is some hardcoding in kubectl.

**Comment by rramkumar1** [comment] 2018-06-06 16:32
@ahmetb Yea mostly likely not an ingress-gce issue. Can we close this?

**Closed** 2018-06-06 17:17 UTC

**Comment by gun1x** [comment] 2019-02-09 19:55
I have the same issue. I added `kubernetes.io/ingress.allow-http: "false"` but the load balancers still deliver HTTP.

**Comment by plainlystated** [comment] 2019-03-31 01:16
same

**Comment by unibit-chenfeng** [comment] 2019-04-15 22:44
same

**Comment by ThanhTuNguyen** [comment] 2019-05-08 07:58
I'm struggling with this, can someone explain this. How can be kubectl or GCE could make an essential issue for security like this

**Comment by gun1x** [comment] 2019-05-08 08:27
> I'm struggling with this, can someone explain this. How can be kubectl or GCE could make an essential issue for security like this

if you think this is bad, also consider there is no way to redirect HTTP to HTTPS.

**Comment by ThanhTuNguyen** [comment] 2019-05-08 10:22
yes it bad, if someone deliberately tries to sneak out your data with a nonsecure protocol.As this post [https://github.com/kubernetes-retired/contrib/issues/1517](kubernetes/ingress-nginx#1517). @ahmetb points out that we must first set up: kubernetes.io/ingress.allow-http: "false" from the first time. That means you are must prepare all ssl-cert and key before we apply yaml file. As I research recently GCE just release a new way to apply new SSL from inside the yaml [https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs](managed-certs) . But i just don't know if it work with ingress.allow-http: "false"

**Comment by MPV** [comment] 2020-01-29 09:32
For anyone returning to this issue:

After annotating with [`kubernetes.io/ingress.allow-http: "false"`](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#disabling_http) **kubectl still reports port 80 on the ingress**, however `gce-ingress` **actually stopped serving requests on port 80**. ✅ 🎉

**Comment by kahootali** [comment] 2020-02-25 11:54
@MPV Still not working, I have added 
`kubernetes.io/ingress.allow-http: "false"`

Still it is serving on http

**Comment by nikashitsa** [comment] 2020-04-07 08:47
Any updates?

**Comment by spencerhance** [comment] 2020-04-07 21:47
@kahootali @nikashitsa what versions of GKE and/or ingress-gce are you using?

**Comment by jasonquick** [comment] 2020-04-08 01:27
For anyone struggling with this the solution is to delete and redeploy your GKE ingress after making configuration changes; GKE Ingresses do not receive configuration updates once they're deployed. 

This also applies to health/readiness checks, etc.

**Comment by spencerhance** [comment] 2020-04-08 03:37
> GKE Ingresses do not receive configuration updates once they're deployed

That is not the expected/intended behavior.  @jasonquick, What version of the controller are you using?

**Comment by zycon** [comment] 2020-05-14 12:07
@jasonquick yeah , true. many times i faced

**Comment by zycon** [comment] 2020-05-14 12:09
any updates,

**Comment by bowei** [comment] 2020-05-19 18:30
Hi everyone -- if you are seeing this issue, please file a new issue with the details wrt to your specific config. It becomes difficult to resolve an already closed issue with a long conversation thread.

**Comment by danielleiszen** [comment] 2020-05-22 00:20
> For anyone struggling with this the solution is to delete and redeploy your GKE ingress after making configuration changes; GKE Ingresses do not receive configuration updates once they're deployed.
> 
> This also applies to health/readiness checks, etc.

Can anyone confirm? Is it documented anywhere?

**Comment by muru** [comment] 2020-05-25 06:42
@danielleiszen At least for readiness checks, it's mentioned in the [Limitations](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#limitations):

> - Changes to a Pod's `readinessProbe` do not affect the Ingress after it is created.

😞

**Comment by andreas-lundgren-storytel** [comment] 2020-06-01 12:56
I faced the same issue. Changed from `allow-http: "true"` to `allow-http: "false"` on an existing ingress and the change didn't have any effect.

Setup:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/backends: '{"k8s-be-30282--07ac49b1e326f89c":"HEALTHY","k8s-be-32137--07ac49b1e326f89c":"HEALTHY"}'
    ingress.kubernetes.io/https-forwarding-rule: k8s-fws-default-accounts-prod-ingress--07ac49b1e326f89c
    ingress.kubernetes.io/https-target-proxy: k8s-tps-default-accounts-prod-ingress--07ac49b1e326f89c
    ingress.kubernetes.io/ssl-cert: k8s-ssl-a676728283231e54-fe6287339b42e8a6--07ac49b1e326f89c
    ingress.kubernetes.io/url-map: k8s-um-default-prod-ingress--07ac49b1e326f89c
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.allow-http":"false","kubernetes.io/ingress.global-static-ip-name":"prod-backend"},"name":"accounts-prod-ingress","namespace":"default"},"spec":{"rules":[{"host":"api.example.net","http":{"paths":[{"backend":{"serviceName":"backend-service","servicePort":80}}]}}],"tls":[{"secretName":"example-net-tls-20200122"}]}}
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: prod-backend
  creationTimestamp: "2020-06-01T12:38:43Z"
  generation: 1
  name: prod-ingress
  namespace: default
  resourceVersion: "2239586"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/prod-ingress
  uid: d41463a6-a404-11ea-baa7-42010a8401fd
spec:
  rules:
  - host: api.example.net
    http:
      paths:
      - backend:
          serviceName: backend-service
          servicePort: 80
  tls:
  - secretName: example-net-tls-20200122
status:
  loadBalancer:
    ingress:
    - ip: 34.120.xxx.xxx
```

**Comment by Gatsby-Lee** [comment] 2020-06-17 04:33
For any one coming here with question "why HTTP request still is handled"
My Env.
* Global External LB
* Ingress-GCE

After I applied updated Ingress kubernetes.io/ingress.allow-http: "false", HTTP still work.
It was like WTF.
 
I run command, "kubectl get ingress". It still show PORTS=80 ( anyway this won't be changed )

After 10min, HTTP starts returning 404 ( blocking )

**Comment by rojomisin** [comment] 2024-07-03 18:36
Whats the secret sauce order of operations here, this caused a simple migration to take much longer.  In the end I just edited the default route to use the TCP:443 backend as this gce-ingress kubernetes pattern does not seem to do the right thing
