### ISSUE TITLE
Not exposed in ingress

### ISSUE THREAD

**Issue by kakarot1994** [kubernetes/ingress-gce#568] opened 2018-12-05 03:58 UTC
I have noticed the feature is not exposed in Ingress.Please help out.

Thanks and Regards

**Comment by rramkumar1** [comment] 2018-12-05 16:39
@kakarot1994 What feature?

**Comment by rramkumar1** [comment] 2019-01-08 17:53
ping @kakarot1994

**Comment by rramkumar1** [comment] 2019-01-14 17:15
I'm going to go ahead and close this since it's not clear what the issue is. 

@kakarot1994 Please re-open once you can provide more details.

**Closed by rramkumar1** 2019-01-14 17:15 UTC
