### ISSUE TITLE
HTTS frontend listener isn't deleted after setting ingress.allow-http: "false" annotation

### ISSUE THREAD

**Issue by giladsh1** [kubernetes/ingress-gce#766] opened 2019-06-10 18:45 UTC
I've created an Ingress controller in my GKE cluster with the default settings.
After applying the manifest, an HTTP(s) load balancer was created with 2 listeners - one for HTTP and another for HTTPS - as expected.

After adding the `kubernetes.io/ingress.allow-http: "false"` annotation to my Ingress config, and applying it to GKE, The HTTP frontend doens't get deleted.
I had to manually delete it via the UI.

config - 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: riscale-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: test-ip
    networking.gke.io/managed-certificates: test-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /d/*
        backend:
          serviceName: http
          servicePort: 2000
      - path: /*
        backend:
          serviceName: web-console
          servicePort: 4200
```

**Comment by MrHohn** [comment] 2019-06-10 20:56
@giladsh1 Thanks for reporting the issue. Closing this as it is pretty much a duplicate of https://github.com/kubernetes/ingress-gce/issues/32. Feel free to reopen otherwise.

**Closed by MrHohn** 2019-06-10 20:56 UTC
