### ISSUE TITLE
Configuring SSL Policies

### ISSUE THREAD

**Issue by artefactop** [kubernetes/ingress-gce#716] opened 2019-04-07 14:57 UTC
I want to configure a different SLL Policy than the default one in my GKE ingresses. In theory, `ingress-gce` has support for it, see https://github.com/kubernetes/ingress-gce/pull/291/files, but I have no idea how to do it.

Could I get some example?

**Comment by rramkumar1** [comment] 2019-04-08 14:55
Closing since this is a duplicate of #246

**Closed by rramkumar1** 2019-04-08 14:55 UTC

**Comment by rdkr** [comment] 2019-04-15 09:48
@artefactop the PR files you linked look like they set Cloud Armor Security Policies not Load Balancing SSL Policies, unfortunately.
