### ISSUE TITLE
support for proper health checks

### ISSUE THREAD

**Issue by leo-baltus** [kubernetes/ingress-gce#65] opened 2017-10-31 13:55 UTC
The GCE loadbalancer perfoms health checks to see if backend are fit to take traffic. These health checks seem to be derived from the readinessProbe defined in the pod the service is pointing to where the service is taken from the ingress.

However, a pod can expose multiple ports where each port can be exposed by a service, but there can be only one readinessProbe on a pod. Also the semantics of each exposed service doe not have to match the semantics of the readinessProbe. 

It would make more sense if the LB-healthcheck would be defined either in the ingress or in the service.

**Comment by nicksardo** [comment] 2017-11-15 19:21
Dupe of #42 
/close

**Closed by nicksardo** 2017-11-15 19:21 UTC
